// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcGHWGmmNOUHZWlKcUB3uSw2za6ECtprE',
    appId: '1:23678658826:web:94ae902100af2a552bb2f3',
    messagingSenderId: '23678658826',
    projectId: 'aarogya-12b89',
    authDomain: 'aarogya-12b89.firebaseapp.com',
    storageBucket: 'aarogya-12b89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaRDYcnTPyFK3WgOi2NlSrprwEGrRKWic',
    appId: '1:23678658826:android:32a1c60eb799ab402bb2f3',
    messagingSenderId: '23678658826',
    projectId: 'aarogya-12b89',
    storageBucket: 'aarogya-12b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-5m6l8VjShUJzxR7aBMx70aPFBRZhOdE',
    appId: '1:23678658826:ios:abf2a562d63f83612bb2f3',
    messagingSenderId: '23678658826',
    projectId: 'aarogya-12b89',
    storageBucket: 'aarogya-12b89.firebasestorage.app',
    iosBundleId: 'com.example.flutterr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-5m6l8VjShUJzxR7aBMx70aPFBRZhOdE',
    appId: '1:23678658826:ios:abf2a562d63f83612bb2f3',
    messagingSenderId: '23678658826',
    projectId: 'aarogya-12b89',
    storageBucket: 'aarogya-12b89.firebasestorage.app',
    iosBundleId: 'com.example.flutterr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcGHWGmmNOUHZWlKcUB3uSw2za6ECtprE',
    appId: '1:23678658826:web:8865fe86193ade902bb2f3',
    messagingSenderId: '23678658826',
    projectId: 'aarogya-12b89',
    authDomain: 'aarogya-12b89.firebaseapp.com',
    storageBucket: 'aarogya-12b89.firebasestorage.app',
  );
}
